/**
 * Mapping of bare GTK CSS node names to web CSS class selectors.
 *
 * GTK CSS targets a widget node tree where selectors like `button` or `headerbar`
 * refer to widget types, not HTML elements. On the web, we remap these to class
 * selectors so that React components can apply the matching className.
 *
 * Some names (like `button`, `label`, `image`) conflict with HTML elements,
 * so ALL bare selectors get a `.gtk-` prefix for consistency.
 */

// Top-level widgets
export const WIDGET_SELECTORS: Record<string, string> = {
  // Buttons
  button: ".gtk-button",
  menubutton: ".gtk-menubutton",
  splitbutton: ".gtk-splitbutton",
  buttoncontent: ".gtk-buttoncontent",
  tabbutton: ".gtk-tabbutton",
  modelbutton: ".gtk-modelbutton",
  colorbutton: ".gtk-colorbutton",
  fontbutton: ".gtk-fontbutton",
  appchooserbutton: ".gtk-appchooserbutton",
  // Entries
  entry: ".gtk-entry",
  text: ".gtk-text",
  editablelabel: ".gtk-editablelabel",
  // Layout
  box: ".gtk-box",
  grid: ".gtk-grid",
  headerbar: ".gtk-headerbar",
  windowcontrols: ".gtk-windowcontrols",
  windowtitle: ".gtk-windowtitle",
  windowhandle: ".gtk-windowhandle",
  actionbar: ".gtk-actionbar",
  searchbar: ".gtk-searchbar",
  toolbar: ".gtk-toolbar",
  centerbox: ".gtk-centerbox",
  viewport: ".gtk-viewport",
  // Lists
  listview: ".gtk-listview",
  list: ".gtk-list",
  row: ".gtk-row",
  columnview: ".gtk-columnview",
  gridview: ".gtk-gridview",
  flowbox: ".gtk-flowbox",
  flowboxchild: ".gtk-flowboxchild",
  iconview: ".gtk-iconview",
  treeview: ".gtk-treeview",
  treeexpander: ".gtk-treeexpander",
  // Containers
  notebook: ".gtk-notebook",
  stack: ".gtk-stack",
  stackswitcher: ".gtk-stackswitcher",
  stacksidebar: ".gtk-stacksidebar",
  overlay: ".gtk-overlay",
  frame: ".gtk-frame",
  expander: ".gtk-expander",
  "expander-widget": ".gtk-expander-widget",
  paned: ".gtk-paned",
  scrolledwindow: ".gtk-scrolledwindow",
  revealer: ".gtk-revealer",
  clamp: ".gtk-clamp",
  // Controls
  scale: ".gtk-scale",
  scrollbar: ".gtk-scrollbar",
  range: ".gtk-range",
  switch: ".gtk-switch",
  spinbutton: ".gtk-spinbutton",
  checkbutton: ".gtk-checkbutton",
  dropdown: ".gtk-dropdown",
  combobox: ".gtk-combobox",
  // Display
  label: ".gtk-label",
  image: ".gtk-image",
  picture: ".gtk-picture",
  video: ".gtk-video",
  separator: ".gtk-separator",
  spinner: ".gtk-spinner",
  progressbar: ".gtk-progressbar",
  levelbar: ".gtk-levelbar",
  calendar: ".gtk-calendar",
  infobar: ".gtk-infobar",
  statusbar: ".gtk-statusbar",
  textview: ".gtk-textview",
  // Popover/Menu
  popover: ".gtk-popover",
  menubar: ".gtk-menubar",
  // Windows/Dialogs
  window: ".gtk-window",
  dialog: ".gtk-dialog",
  "dialog-host": ".gtk-dialog-host",
  messagedialog: ".gtk-messagedialog",
  // Color
  colorswatch: ".gtk-colorswatch",
  colorchooser: ".gtk-colorchooser",
  // Emoji
  emojichooser: ".gtk-emojichooser",
  emoji: ".gtk-emoji",
  "emoji-completion-row": ".gtk-emoji-completion-row",
  // File
  filechooser: ".gtk-filechooser",
  filelistcell: ".gtk-filelistcell",
  filethumbnail: ".gtk-filethumbnail",
  pathbar: ".gtk-pathbar",
  placessidebar: ".gtk-placessidebar",
  placesview: ".gtk-placesview",
  // Toggle group
  "toggle-group": ".gtk-toggle-group",
  toggle: ".gtk-toggle",
  // Tooltip
  tooltip: ".gtk-tooltip",
  // Print
  paper: ".gtk-paper",
  // Shortcuts
  shortcut: ".gtk-shortcut",
  "shortcut-label": ".gtk-shortcut-label",
  "shortcuts-section": ".gtk-shortcuts-section",
  // Adwaita-specific widgets
  avatar: ".gtk-avatar",
  banner: ".gtk-banner",
  "status-page": ".gtk-status-page",
  statuspage: ".gtk-statuspage",
  "bottom-sheet": ".gtk-bottom-sheet",
  "adaptive-preview": ".gtk-adaptive-preview",
  "tab-bar": ".gtk-tab-bar",
  tabbar: ".gtk-tabbar",
  "tab-overview": ".gtk-tab-overview",
  taboverview: ".gtk-taboverview",
  tabview: ".gtk-tabview",
  tabbox: ".gtk-tabbox",
  tabboxchild: ".gtk-tabboxchild",
  tabgrid: ".gtk-tabgrid",
  tabgridchild: ".gtk-tabgridchild",
  tabthumbnail: ".gtk-tabthumbnail",
  "inline-view-switcher": ".gtk-inline-view-switcher",
  viewswitcher: ".gtk-viewswitcher",
  viewswitcherbar: ".gtk-viewswitcherbar",
  viewswitchertitle: ".gtk-viewswitchertitle",
  "navigation-view": ".gtk-navigation-view",
  "overlay-split-view": ".gtk-overlay-split-view",
  leaflet: ".gtk-leaflet",
  flap: ".gtk-flap",
  "floating-sheet": ".gtk-floating-sheet",
  sheet: ".gtk-sheet",
  toolbarview: ".gtk-toolbarview",
  preferencesgroup: ".gtk-preferencesgroup",
  preferencespage: ".gtk-preferencespage",
  toast: ".gtk-toast",
  indicatorbin: ".gtk-indicatorbin",
};

// Internal structural elements (parts of widgets, not standalone)
export const INTERNAL_SELECTORS: Record<string, string> = {
  trough: ".gtk-trough",
  slider: ".gtk-slider",
  highlight: ".gtk-highlight",
  fill: ".gtk-fill",
  marks: ".gtk-marks",
  mark: ".gtk-mark",
  indicator: ".gtk-indicator",
  value: ".gtk-value",
  arrow: ".gtk-arrow",
  contents: ".gtk-contents",
  header: ".gtk-header",
  tabs: ".gtk-tabs",
  tab: ".gtk-tab",
  undershoot: ".gtk-undershoot",
  overshoot: ".gtk-overshoot",
  dimming: ".gtk-dimming",
  shadow: ".gtk-shadow",
  border: ".gtk-border",
  "block-cursor": ".gtk-block-cursor",
  placeholder: ".gtk-placeholder",
  progress: ".gtk-progress",
  cell: ".gtk-cell",
  check: ".gtk-check",
  radio: ".gtk-radio",
  dnd: ".gtk-dnd",
  selection: ".gtk-selection",
  block: ".gtk-block",
  title: ".gtk-title",
  item: ".gtk-item",
  color: ".gtk-color",
  widget: ".gtk-widget",
  "cursor-handle": ".gtk-cursor-handle",
  "drag-handle": ".gtk-drag-handle",
  dndtarget: ".gtk-dndtarget",
  drawing: ".gtk-drawing",
  magnifier: ".gtk-magnifier",
  rubberband: ".gtk-rubberband",
  "sort-indicator": ".gtk-sort-indicator",
  spin: ".gtk-spin",
  plane: ".gtk-plane",
  acceleditor: ".gtk-acceleditor",
  accelerator: ".gtk-accelerator",
};

/** All selector mappings combined. */
export const ALL_SELECTORS: Record<string, string> = {
  ...WIDGET_SELECTORS,
  ...INTERNAL_SELECTORS,
};
