FROM ghcr.io/gtk-rs/gtk4-rs/gtk4:latest

RUN dnf install -y sassc unzip cargo xorg-x11-server-Xvfb \
    libicu libjpeg-turbo libwebp flite pcre libffi mesa-libgbm libdrm \
    atk at-spi2-atk libXcomposite libXdamage libXrandr libX11 \
    nss nspr alsa-lib cups-libs libXScrnSaver pango

RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

RUN bunx playwright install chromium firefox

WORKDIR /workspace
